require("dotenv").config({ path: require("path").join(__dirname, "..", ".env") });
const { countAll, wipe, replaceAllAds, dbPath } = require("./db");

// ensure demo avatars exist
try {
  require("./gen-avatars.js");
} catch (e) {
  console.warn("Avatar gen skipped:", e.message);
}

const reset = process.argv.includes("--reset");

const ZONE_MAP = {
  levante: "Playa de Levante",
  poniente: "Playa de Poniente",
  "rincon-de-loix": "Rincón de Loix",
  "casco-antiguo": "Casco Antiguo",
  "nueva-poniente": "Nueva Poniente",
  foietes: "Foietes",
};

const DEMO = [
  {
    id: "sofia-levante",
    name: "Sofía",
    title: "Sofía española elegante — Levante Benidorm",
    age: 24,
    zoneSlug: "levante",
    locationDetail: "Playa de Levante · cerca del casino",
    nationality: "Española",
    height: "1.68 m",
    bodyType: "Delgada",
    hair: "Castaño",
    languages: ["ES", "EN"],
    price: 150,
    tags: ["vip", "verified"],
    services: ["Masajes", "GFE", "Hotel"],
    desc: "Discreta y elegante en el corazón de Levante. Citas en hotel o apartamento en Benidorm. Fotos reales.",
    descEn: "Discreet and elegant in the heart of Levante. Hotel or apartment dates in Benidorm.",
    phone: "34600000001",
    featured: true,
    online: true,
    views: 1284,
    plan: "vip",
    independent: true,
    incall: true,
    outcall: true,
    available24h: false,
    schedule: "11:00 – 02:00",
  },
  {
    id: "luna-rincon",
    name: "Luna",
    title: "Luna latina nueva en Rincón de Loix",
    age: 27,
    zoneSlug: "rincon-de-loix",
    locationDetail: "Rincón de Loix · zona pubs",
    nationality: "Latina",
    height: "1.65 m",
    bodyType: "Curvy",
    hair: "Negro",
    languages: ["ES", "EN"],
    price: 120,
    tags: ["new", "verified"],
    services: ["Compañía", "Salidas", "Hotel"],
    desc: "Nueva en Rincón de Loix. Ideal para turistas cerca de la zona británica de Benidorm.",
    descEn: "New in Rincón de Loix. Ideal for tourists near Benidorm's British area.",
    phone: "34600000002",
    featured: true,
    online: true,
    views: 892,
    plan: "free",
    independent: true,
    incall: true,
    outcall: true,
    available24h: false,
    schedule: "Flexible",
  },
  {
    id: "valentina-poniente",
    name: "Valentina",
    title: "Valentina VIP italiana — Poniente",
    age: 29,
    zoneSlug: "poniente",
    locationDetail: "Playa de Poniente",
    nationality: "Italiana",
    height: "1.72 m",
    bodyType: "Atlética",
    hair: "Rubio",
    languages: ["ES", "EN", "IT"],
    price: 180,
    tags: ["vip", "verified"],
    services: ["GFE", "Cena", "Hotel"],
    desc: "Experiencia VIP en Poniente. Ambiente relajado y citas de calidad en Benidorm.",
    descEn: "VIP experience in Poniente. Relaxed vibe and quality dates in Benidorm.",
    phone: "34600000003",
    featured: true,
    online: false,
    views: 2103,
    plan: "vip",
    independent: true,
    incall: true,
    outcall: true,
    available24h: false,
    schedule: "16:00 – 03:00",
  },
  {
    id: "mia-casco",
    name: "Mía",
    title: "Mía real en Casco Antiguo Benidorm",
    age: 23,
    zoneSlug: "casco-antiguo",
    locationDetail: "Casco Antiguo · centro",
    nationality: "Española",
    height: "1.62 m",
    bodyType: "Petite",
    hair: "Moreno",
    languages: ["ES"],
    price: 100,
    tags: ["verified"],
    services: ["Masajes", "Domicilio"],
    desc: "Citas en el casco antiguo de Benidorm. Cercana, simpática y 100% real.",
    descEn: "Dates in Benidorm old town. Friendly, real and local.",
    phone: "34600000004",
    featured: true,
    online: true,
    views: 654,
    plan: "free",
    independent: true,
    incall: true,
    outcall: false,
    available24h: false,
    schedule: "12:00 – 00:00",
  },
  {
    id: "carla-nueva-poniente",
    name: "Carla",
    title: "Carla colombiana — Nueva Poniente",
    age: 31,
    zoneSlug: "nueva-poniente",
    locationDetail: "Nueva Poniente residencial",
    nationality: "Colombiana",
    height: "1.70 m",
    bodyType: "Curvy",
    hair: "Castaño",
    languages: ["ES", "EN"],
    price: 140,
    tags: ["vip"],
    services: ["Hotel", "Salidas", "GFE"],
    desc: "Disponible en Nueva Poniente y zona residencial de Benidorm. WhatsApp prioritario.",
    descEn: "Available in Nueva Poniente residential area. WhatsApp priority.",
    phone: "34600000005",
    featured: false,
    online: false,
    views: 441,
    plan: "vip",
    independent: true,
    incall: false,
    outcall: true,
    available24h: false,
    schedule: "Flexible",
  },
  {
    id: "nina-levante",
    name: "Nina",
    title: "Nina premium 24h — Levante TOP",
    age: 26,
    zoneSlug: "levante",
    locationDetail: "Levante · primera línea",
    nationality: "Rusa",
    height: "1.74 m",
    bodyType: "Modelo",
    hair: "Rubio",
    languages: ["ES", "EN", "RU", "DE"],
    price: 200,
    tags: ["vip", "verified", "new"],
    services: ["VIP", "Hotel", "Eventos"],
    desc: "Perfil premium en Levante. Para quienes buscan lo mejor de Benidorm.",
    descEn: "Premium profile in Levante. For those who want the best of Benidorm.",
    phone: "34600000006",
    featured: true,
    online: true,
    views: 1876,
    plan: "top",
    independent: true,
    incall: true,
    outcall: true,
    available24h: true,
    schedule: "24h",
  },
  {
    id: "aisha-foietes",
    name: "Aisha",
    title: "Aisha discreta — Foietes / Cala",
    age: 25,
    zoneSlug: "foietes",
    locationDetail: "Foietes · cerca Cala Finestrat",
    nationality: "Marroquí",
    height: "1.66 m",
    bodyType: "Delgada",
    hair: "Negro",
    languages: ["ES", "FR", "AR"],
    price: 110,
    tags: ["verified"],
    services: ["Masajes", "Hotel"],
    desc: "Zona Foietes / Cala de Finestrat. Discreción total en Benidorm y alrededores.",
    descEn: "Foietes / Cala de Finestrat area. Total discretion in Benidorm.",
    phone: "34600000007",
    featured: false,
    online: true,
    views: 318,
    plan: "free",
    independent: true,
    incall: true,
    outcall: true,
    available24h: false,
    schedule: "10:00 – 22:00",
  },
  {
    id: "emma-poniente",
    name: "Emma",
    title: "Emma British — Poniente Benidorm",
    age: 28,
    zoneSlug: "poniente",
    locationDetail: "Poniente · zona residencial",
    nationality: "Británica",
    height: "1.69 m",
    bodyType: "Natural",
    hair: "Rubio",
    languages: ["EN", "ES", "NL"],
    price: 160,
    tags: ["verified"],
    services: ["Compañía", "Cena", "Hotel"],
    desc: "Perfecta para turistas de habla inglesa en la zona de Poniente, Benidorm.",
    descEn: "Perfect for English-speaking tourists in Poniente, Benidorm.",
    phone: "34600000008",
    featured: false,
    online: false,
    views: 977,
    plan: "free",
    independent: true,
    incall: true,
    outcall: true,
    available24h: false,
    schedule: "Flexible",
  },
  {
    id: "isabella-levante",
    name: "Isabella",
    title: "Isabella brasileña GFE — Levante",
    age: 30,
    zoneSlug: "levante",
    locationDetail: "Levante · Calle Gerona",
    nationality: "Brasileña",
    height: "1.67 m",
    bodyType: "Curvy",
    hair: "Castaño",
    languages: ["ES", "EN", "PT"],
    price: 170,
    tags: ["vip", "verified"],
    services: ["GFE", "Hotel", "Masajes"],
    desc: "Escort brasileña en Levante Benidorm. Citas de calidad y muy buena presencia.",
    descEn: "Brazilian escort in Levante Benidorm. Quality dates, great presence.",
    phone: "34600000009",
    featured: true,
    online: true,
    views: 1432,
    plan: "vip",
    independent: true,
    incall: true,
    outcall: true,
    available24h: false,
    schedule: "14:00 – 04:00",
  },
  {
    id: "chloe-rincon",
    name: "Chloe",
    title: "Chloe francesa VIP — Rincón de Loix",
    age: 22,
    zoneSlug: "rincon-de-loix",
    locationDetail: "Rincón de Loix · The Square",
    nationality: "Francesa",
    height: "1.71 m",
    bodyType: "Modelo",
    hair: "Rubio",
    languages: ["FR", "EN", "ES", "DE"],
    price: 190,
    tags: ["new", "vip"],
    services: ["VIP", "Hotel", "Salidas"],
    desc: "Nueva VIP en Rincón de Loix. Ideal para turistas en la zona de pubs de Benidorm.",
    descEn: "New VIP in Rincón de Loix. Ideal near Benidorm's pub strip.",
    phone: "34600000010",
    featured: true,
    online: true,
    views: 521,
    plan: "vip",
    independent: true,
    incall: true,
    outcall: true,
    available24h: true,
    schedule: "24h",
  },
  {
    id: "laura-casco",
    name: "Laura",
    title: "Laura madura y discreta — Casco Antiguo",
    age: 33,
    zoneSlug: "casco-antiguo",
    locationDetail: "Casco Antiguo · Old Town",
    nationality: "Española",
    height: "1.64 m",
    bodyType: "Natural",
    hair: "Castaño",
    languages: ["ES", "EN", "NO"],
    price: 130,
    tags: ["verified"],
    services: ["Compañía", "Cena", "Hotel"],
    desc: "Experiencia madura y discreta en el centro histórico de Benidorm.",
    descEn: "Mature, discreet company in Benidorm old town.",
    phone: "34600000011",
    featured: false,
    online: false,
    views: 708,
    plan: "free",
    independent: true,
    incall: true,
    outcall: true,
    available24h: false,
    schedule: "18:00 – 02:00",
  },
  {
    id: "daria-levante",
    name: "Daria",
    title: "Daria modelo 24h — Paseo Levante",
    age: 25,
    zoneSlug: "levante",
    locationDetail: "Paseo de Levante",
    nationality: "Ucraniana",
    height: "1.73 m",
    bodyType: "Modelo",
    hair: "Rubio",
    languages: ["ES", "EN", "RU", "PL"],
    price: 175,
    tags: ["verified", "vip"],
    services: ["GFE", "Hotel", "VIP"],
    desc: "Modelo y escort en el paseo de Levante. Fotos reales, Benidorm 24h.",
    descEn: "Model escort on Levante promenade. Real photos, Benidorm 24h.",
    phone: "34600000012",
    featured: true,
    online: true,
    views: 1655,
    plan: "top",
    independent: true,
    incall: true,
    outcall: true,
    available24h: true,
    schedule: "24h",
  },
];

function demoPhotos(id) {
  return [1, 2, 3].map((n) => `/uploads/demo-${id}-${n}.svg`);
}

function toAd(d) {
  const now = new Date().toISOString();
  const photos = demoPhotos(d.id);
  return {
    id: d.id,
    name: d.name,
    title: d.title || d.name,
    age: d.age,
    zone: ZONE_MAP[d.zoneSlug],
    zoneSlug: d.zoneSlug,
    locationDetail: d.locationDetail || "",
    nationality: d.nationality,
    height: d.height,
    bodyType: d.bodyType || "",
    hair: d.hair || "",
    languages: d.languages,
    price: d.price,
    tags: d.tags,
    services: d.services,
    desc: d.desc,
    descEn: d.descEn,
    phone: d.phone,
    photo: photos[0],
    photos,
    editPin: `demo-${d.id.slice(0, 8)}`,
    featured: !!d.featured,
    online: !!d.online,
    views: d.views || 0,
    status: "active",
    plan: d.plan || "free",
    source: "demo",
    independent: d.independent !== false,
    incall: d.incall !== false,
    outcall: d.outcall !== false,
    available24h: !!d.available24h,
    schedule: d.schedule || "Flexible",
    createdAt: now,
    updatedAt: now,
    lastBump: now,
  };
}

if (reset) {
  wipe();
  console.log("DB wiped.");
}

if (countAll() === 0 || reset) {
  replaceAllAds(DEMO.map(toAd));
  console.log(`Seeded ${DEMO.length} ads with photos → ${dbPath}`);
  console.log("Demo manage PIN example: phone 34600000001 · pin demo-sofia-le");
} else {
  console.log(`DB already has ${countAll()} ads. Use --reset to reseed. (${dbPath})`);
}
